
version: '3'

services:
  creative:
    image: node:latest
    #ports:
    #  - "3000:3000"
    volumes:
      - ./Server:/app
    restart: always
    working_dir: /app
    entrypoint:
      - yarn
      - start
networks:
  default:
    external:
      name: production_default
