
version: '3'

services:
  creative:
    image: node:latest
    ports:
      - "80:3000"
    volumes:
      - ./Server:/app
    restart: always
    working_dir: /app
    networks:
      - default
    entrypoint:
      - yarn
      - start
